### ISSUE TITLE
does this mod work with Mythic-Magic-Mayhem

### ISSUE THREAD

**Issue by Hadeszeus999** [Balkoth-dev/WOTR_PATH_OF_RAGE#10]
does this mod work with https://github.com/YLMstring/Mythic-Magic-Mayhem

also does your mod modify The mythic spell book merge 

Sorry about asking this

**Comment by Balkoth-dev** [comment]
This mod does not modify the spellbook in any way. It should work with Mythic Magic Mayhem fine.

**Comment by Hadeszeus999** [comment]
thank you for answering My question
