### ISSUE TITLE
Demon Polypmorph is checking for demon blast and not creating the blueprints causing save issues/

### ISSUE THREAD

**Issue by factubsio** [Balkoth-dev/WOTR_PATH_OF_RAGE#2]
https://github.com/Balkoth-dev/WOTR_PATH_OF_RAGE/blob/519c1a8c764c9869080c037bc041b9cfb5b220d9/NewFeatures/DemonPolymorph.cs#L48

**Comment by Balkoth-dev** [comment]
Removed that setting so the blueprints will be created each time the game loads.
