### ISSUE TITLE
brimorak possible bug [Needs More Information]

### ISSUE THREAD

**Issue by templer10** [Balkoth-dev/WOTR_PATH_OF_RAGE#5]
at the moment aspect of brimorak adds it's bonus damage per die twice - not sure if it's a mod issue or maybe the base game was fixed so it's doubled up now?

EDIT - yup checked - when i turned off the option for the brimorack fix iam still getiing the 2 damage per die.

also - demonic rage currently gives +2 caster level and it's supposed to give +2 to cl only for purpose of overcoming damage reduction.

**Comment by Balkoth-dev** [comment]
This is probably because you have both TTT-Base and PoR installed. 10/11/2022 update has dealt with this by disabling PoR's update. 

Caster Level has nothing to do with damage reduction.

**Comment by Balkoth-dev** [comment]
10/11/2022 update should solve the stacking of brimorak and TTT-Base. Caster level from Demon Rage is expected.
