### ISSUE TITLE
Request: Fixing Aspekt of Deskari vanilla bug

### ISSUE THREAD

**Issue by eilersn** [Balkoth-dev/WOTR_PATH_OF_RAGE#6]
The Demon Lord Aspect of Deskari is supposed to allow physical damage to ignore Damage Reduction, but doesn't work. This seems to be a vanilla bug and not caused by PATH OF RAGE itself, although the mod might be a fitting platform to fix bugs with the Demon path.

Tested without any mods apart from ToyBox to level quickly and spawn in a Large Fire Elemental.

**Comment by Balkoth-dev** [comment]
Looks like Owlcat got to this before I did. Should be fixed in 2.1.0j BETA of the game.
